actions:
- priority_header: '2'
  subject: c7n notifcation
  template: default
  to: todo@todo.com
  transport: {queue: 'https://sqs.us-east-1.amazonaws.com/1234567890/c7n-todo', type: sqs}
  type: notify
description: 'AWS::SageMaker::EndpointConfig property [EndpointConfigName] should
  exist, consider default values of [ {''Ref'': ''TODO''} ] '
filters:
- {key: EndpointConfigName, op: not-equal, type: sagemaker, value: 'type:exists'}
mode:
  events: [RunInstances]
  role: CloudCustodian
  type: cloudtrail
name: CustomAWSSageMakerEndpointConfigEndpointConfigNameRule
resource: aws.sagemaker
