actions:
- priority_header: '2'
  subject: c7n notifcation
  template: default
  to: todo@todo.com
  transport: {queue: 'https://sqs.us-east-1.amazonaws.com/1234567890/c7n-todo', type: sqs}
  type: notify
description: 'AWS::Pinpoint::ApplicationSettings property [CloudWatchMetricsEnabled]
  should exist, consider default values of [ true ] '
filters:
- {key: CloudWatchMetricsEnabled, op: not-equal, type: pinpoint, value: 'type:exists'}
mode:
  events: [RunInstances]
  role: CloudCustodian
  type: cloudtrail
name: CustomAWSPinpointApplicationSettingsCloudWatchMetricsEnabledRule
resource: aws.pinpoint
